spring:
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  datasource:
    url: jdbc:postgresql://localhost:5432/smartOrder
    username: minho
    password: 1234
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
  messages:
    basename: config/messages
